src/Entity/Pelicula.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PeliculaRepository")
 */
class Pelicula
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titulo;

    /**
     * @ORM\Column(type="text")
     */
    private $Resumen;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Director;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Actores;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Escritores;

    /**
     * @ORM\Column(type="integer")
     */
    private $Duracion;

    /**
     * @ORM\Column(type="integer")
     */
    private $Edad;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Genero;

    /**
     * @ORM\Column(type="date")
     */
    private $Fecha_salida;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comentario", mappedBy="Pelicula")
     */
    private $comentarios;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Valoracion", mappedBy="Pelicula")
     */
    private $valoracions;

    public function __construct()
    {
        $this->comentarios = new ArrayCollection();
        $this->valoracions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->Titulo;
    }

    public function setTitulo(string $Titulo): self
    {
        $this->Titulo = $Titulo;

        return $this;
    }

    public function getResumen(): ?string
    {
        return $this->Resumen;
    }

    public function setResumen(string $Resumen): self
    {
        $this->Resumen = $Resumen;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->Director;
    }

    public function setDirector(string $Director): self
    {
        $this->Director = $Director;

        return $this;
    }

    public function getActores(): ?string
    {
        return $this->Actores;
    }

    public function setActores(string $Actores): self
    {
        $this->Actores = $Actores;

        return $this;
    }

    public function getEscritores(): ?string
    {
        return $this->Escritores;
    }

    public function setEscritores(string $Escritores): self
    {
        $this->Escritores = $Escritores;

        return $this;
    }

    public function getDuracion(): ?int
    {
        return $this->Duracion;
    }

    public function setDuracion(int $Duracion): self
    {
        $this->Duracion = $Duracion;

        return $this;
    }

    public function getEdad(): ?int
    {
        return $this->Edad;
    }

    public function setEdad(int $Edad): self
    {
        $this->Edad = $Edad;

        return $this;
    }

    public function getGenero(): ?string
    {
        return $this->Genero;
    }

    public function setGenero(string $Genero): self
    {
        $this->Genero = $Genero;

        return $this;
    }

    public function getFechaSalida(): ?\DateTimeInterface
    {
        return $this->Fecha_salida;
    }

    public function setFechaSalida(\DateTimeInterface $Fecha_salida): self
    {
        $this->Fecha_salida = $Fecha_salida;

        return $this;
    }

    /**
     * @return Collection|Comentario[]
     */
    public function getComentarios(): Collection
    {
        return $this->comentarios;
    }

    public function addComentario(Comentario $comentario): self
    {
        if (!$this->comentarios->contains($comentario)) {
            $this->comentarios[] = $comentario;
            $comentario->setPelicula($this);
        }

        return $this;
    }

    public function removeComentario(Comentario $comentario): self
    {
        if ($this->comentarios->contains($comentario)) {
            $this->comentarios->removeElement($comentario);
            // set the owning side to null (unless already changed)
            if ($comentario->getPelicula() === $this) {
                $comentario->setPelicula(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Valoracion[]
     */
    public function getValoracions(): Collection
    {
        return $this->valoracions;
    }

    public function addValoracion(Valoracion $valoracion): self
    {
        if (!$this->valoracions->contains($valoracion)) {
            $this->valoracions[] = $valoracion;
            $valoracion->setPelicula($this);
        }

        return $this;
    }

    public function removeValoracion(Valoracion $valoracion): self
    {
        if ($this->valoracions->contains($valoracion)) {
            $this->valoracions->removeElement($valoracion);
            // set the owning side to null (unless already changed)
            if ($valoracion->getPelicula() === $this) {
                $valoracion->setPelicula(null);
            }
        }

        return $this;
    }
}

src/Entity/Serie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SerieRepository")
 */
class Serie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titulo;

    /**
     * @ORM\Column(type="text")
     */
    private $Resumen;

    /**
     * @ORM\Column(type="integer")
     */
    private $Temporadas;

    /**
     * @ORM\Column(type="integer")
     */
    private $Capitulos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Genero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Actores;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comentario", mappedBy="Serie")
     */
    private $comentarios;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Valoracion", mappedBy="Serie")
     */
    private $valoracions;

    public function __construct()
    {
        $this->comentarios = new ArrayCollection();
        $this->valoracions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->Titulo;
    }

    public function setTitulo(string $Titulo): self
    {
        $this->Titulo = $Titulo;

        return $this;
    }

    public function getResumen(): ?string
    {
        return $this->Resumen;
    }

    public function setResumen(string $Resumen): self
    {
        $this->Resumen = $Resumen;

        return $this;
    }

    public function getTemporadas(): ?int
    {
        return $this->Temporadas;
    }

    public function setTemporadas(int $Temporadas): self
    {
        $this->Temporadas = $Temporadas;

        return $this;
    }

    public function getCapitulos(): ?int
    {
        return $this->Capitulos;
    }

    public function setCapitulos(int $Capitulos): self
    {
        $this->Capitulos = $Capitulos;

        return $this;
    }

    public function getGenero(): ?string
    {
        return $this->Genero;
    }

    public function setGenero(string $Genero): self
    {
        $this->Genero = $Genero;

        return $this;
    }

    public function getActores(): ?string
    {
        return $this->Actores;
    }

    public function setActores(string $Actores): self
    {
        $this->Actores = $Actores;

        return $this;
    }

    /**
     * @return Collection|Comentario[]
     */
    public function getComentarios(): Collection
    {
        return $this->comentarios;
    }

    public function addComentario(Comentario $comentario): self
    {
        if (!$this->comentarios->contains($comentario)) {
            $this->comentarios[] = $comentario;
            $comentario->setSerie($this);
        }

        return $this;
    }

    public function removeComentario(Comentario $comentario): self
    {
        if ($this->comentarios->contains($comentario)) {
            $this->comentarios->removeElement($comentario);
            // set the owning side to null (unless already changed)
            if ($comentario->getSerie() === $this) {
                $comentario->setSerie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Valoracion[]
     */
    public function getValoracions(): Collection
    {
        return $this->valoracions;
    }

    public function addValoracion(Valoracion $valoracion): self
    {
        if (!$this->valoracions->contains($valoracion)) {
            $this->valoracions[] = $valoracion;
            $valoracion->setSerie($this);
        }

        return $this;
    }

    public function removeValoracion(Valoracion $valoracion): self
    {
        if ($this->valoracions->contains($valoracion)) {
            $this->valoracions->removeElement($valoracion);
            // set the owning side to null (unless already changed)
            if ($valoracion->getSerie() === $this) {
                $valoracion->setSerie(null);
            }
        }

        return $this;
    }
}

src/Entity/Valoracion.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ValoracionRepository")
 */
class Valoracion
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="valoracions")
     */
    private $Autor;

    /**
     * @ORM\Column(type="date")
     */
    private $Fecha;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(0)
     * @Assert\LessThanOrEqual(10)
     */
    private $Valoracion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pelicula", inversedBy="valoracions")
     */
    private $Pelicula;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Serie", inversedBy="valoracions")
     */
    private $Serie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAutor(): ?User
    {
        return $this->Autor;
    }

    public function setAutor(?User $Autor): self
    {
        $this->Autor = $Autor;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->Fecha;
    }

    public function setFecha(\DateTimeInterface $Fecha): self
    {
        $this->Fecha = $Fecha;

        return $this;
    }

    public function getValoracion(): ?int
    {
        return $this->Valoracion;
    }

    public function setValoracion(int $Valoracion): self
    {
        $this->Valoracion = $Valoracion;

        return $this;
    }

    public function getPelicula(): ?Pelicula
    {
        return $this->Pelicula;
    }

    public function setPelicula(?Pelicula $Pelicula): self
    {
        $this->Pelicula = $Pelicula;

        return $this;
    }

    public function getSerie(): ?Serie
    {
        return $this->Serie;
    }

    public function setSerie(?Serie $Serie): self
    {
        $this->Serie = $Serie;

        return $this;
    }
}

templates/proyecto/listaPeliculas.html.twig
{% extends 'base.html.twig' %}

{% block title %}CinemaPlus-ListaPeliculas{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ path('inicio') }}">Inicio</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ path('peliculas') }}">Peliculas</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ path('series') }}">Series</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ path('register') }}">Registrar</a>
        </li>
        {% if app.user != null %}
        <li class="nav-item">
            <a class="nav-link" href="{{ path('logout') }}">Salir</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{{ path('login') }}">Login</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

{% block body %}
<div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
    <h2>Listado de peliculas</h2>
    <br /><br />
    <div class="col-4 col-sm-4 col-xl-4">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
    <br /><br />
    <div id="lista-peliculas">
        {% for pelicula in peliculas %}
            <div class="row">
                <div class="col-12 col-lg-12 col-xl-4">
                    <a href="{{ path('pelicula', {'id': pelicula.id}) }}"><img src="{{ asset('images/imagen' ~ pelicula.id ~ '.jpg') }}" alt={{ pelicula.titulo }} class="img-responsive fit-image imagenLista"></a>
                </div>
                <div class="col-12 col-lg-12 col-xl-8">
                    <a class="enlacePeli" href="{{ path('pelicula', {'id': pelicula.id}) }}"><h3>{{ pelicula.Titulo }}</h3></a>
                    <p>{{ pelicula.Actores }}</p>
                    <p>{{ pelicula.Director }}</p>
                    <p>{{ pelicula.Resumen }}</p>
                    <a class="enlacePeli" href="{{ path('pelicula', {'id': pelicula.id}) }}"><p>Leer mas...</p></a>
                </div>
            </div>
            <br /><br />
        {% endfor %}
    </div>
    
    {% if app.user != null %}
        {% for rol in user %}
            {% for rol1 in rol.roles %}
                {% if app.user.username == rol.username and rol1 == "admin" %}
                    <p><a class="enlaceboton" href="{{ path('peliculaNueva') }}">Añadir pelicula</a></p>
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/proyecto/listaSeries.html.twig
{% extends 'base.html.twig' %}

{% block title %}CinemaPlus-ListaSeries{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ path('inicio') }}">Inicio</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ path('peliculas') }}">Peliculas</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ path('series') }}">Series</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ path('register') }}">Registrar</a>
        </li>
        {% if app.user != null %}
        <li class="nav-item">
            <a class="nav-link" href="{{ path('logout') }}">Salir</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{{ path('login') }}">Login</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

{% block body %}
<div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
    <h2>Listado de Series</h2>
    <br /><br />
    <div class="col-4 col-sm-4 col-xl-4">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
    <br /><br />
    {% for serie in series %}
        <div class="row">
            <div class="col-12 col-lg-12 col-xl-4">
                <a href="{{ path('serie', {'id': serie.id}) }}"><img src="{{ asset('images/serie' ~ serie.id ~ '.jpg') }}" alt={{ serie.titulo }} class="img-responsive fit-image imagenLista"></a>
            </div>
            <div class="col-12 col-lg-12 col-xl-8">
                <a class="enlacePeli" href="{{ path('serie', {'id': serie.id}) }}"><h3>{{ serie.titulo }}</h3></a>
                <p>{{ serie.actores }}</p>
                <p>{{ serie.resumen }}</p>
                <a class="enlacePeli" href="{{ path('serie', {'id': serie.id}) }}"><p>Leer mas...</p></a>
            </div>
        </div>
        <br /><br />
    {% endfor %}

    {% if app.user != null %}
        {% for rol in user %}
            {% for rol1 in rol.roles %}
                {% if app.user.username == rol.username and rol1 == "admin" %}
                    <p><a class="enlaceboton" href="{{ path('serieNueva') }}">Añadir serie</a></p>
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% endif %}

</div>
{% endblock %}

templates/proyecto/pelicula.html.twig
{# templates/proyecto/noticia.html.twig #}
{% extends 'base.html.twig' %}
{% block title %}{{ pelicula.Titulo }}{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ path('inicio') }}">Inicio</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ path('pelicula', {'id': pelicula.id}) }}">{{ pelicula.Titulo }}</a>
        </li>
    </ul>
</div>
{% endblock %}
{% block body %}
    <div class="row">

        <div class="col-12 col-sm-8 col-xl-3 detallePeli">
            <img src="{{ asset('images/imagen' ~ pelicula.id ~ '.jpg') }}" alt={{ pelicula.titulo }} />
        </div>
        <div class="col-12 col-sm-8 col-xl-8 detallePeli">
            <h2>Título: {{ pelicula.Titulo }}</h2>
            <p><strong>Resumen:</strong> {{ pelicula.Resumen }}</p>
            <p><strong>Director:</strong> {{ pelicula.Director }}</p>
            <p><strong>Actores:</strong> {{ pelicula.Actores }}</p>
            <p><strong>Escritores:</strong> {{ pelicula.Escritores }}</p>
            <p><strong>Edad recomendada:</strong> {{ pelicula.Edad }}</p>
            <p><strong>Duración:</strong> {{ pelicula.Duracion }}</p>
            <p><strong>Género:</strong> {{ pelicula.Genero }}</p>
            <p><strong>Fecha de lanzamiento:</strong> {{ pelicula.fechaSalida|date("d/m/Y") }}</p>
            {% if pelicula.valoracions.count() == 0 %}
                <p><strong>Valoración media:</strong> Esta película aún no ha sido valorada.</p>
            {% else %}
                {% set suma = 0 %}
                {% for valoracion in pelicula.valoracions %}
                    {% set numeros = valoracion.valoracion %}
                    {% set suma = numeros + suma %}
                {% endfor %}
                {% set media = suma / pelicula.valoracions.count() %}
                <p><strong>Valoración media:</strong> {{ media|round(1, 'floor') }}/10</p>
            {% endif %}
            <br />
            {{ form_start(form) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
    </div>
    <br /><br />
    <div class="row comentario">
        {{ form_start(form2) }}
        {{ form_widget(form2) }}
        {{ form_end(form2) }}

        <ul>
        {% for comentario in pelicula.comentarios %}
            <li class='bloqueComentario'>
                <p>
                    {% if comentario.Autor != null %}
                        <strong>{{ comentario.Autor.username }}</strong>
                    {% else %}
                        <strong>Anónimo</strong>
                    {% endif %}
                    en {{ comentario.fecha|date("d/m/Y") }}:
                </p>
                <p>{{ comentario.texto }}</p>
            </li>
        {% else %}
            <li>No hay comentarios</li>
        {% endfor %}
        </ul>
    </div>


    <br /><br />
    <div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
        <p><a class="enlaceboton" href="{{ path('descargarPDFPeli', {'id' : pelicula.id}) }}">Descargar PDF</a></p>
    </div>

    <div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
        {% if app.user != null %}
            {% for rol in user %}
                {% for rol1 in rol.roles %}
                    {% if app.user.username == rol.username and rol1 == "admin" %}
                        <p><a class="enlaceboton" href="{{ path('borrarPelicula', {'id' : pelicula.id}) }}">Borrar pelicula</a></p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
        {% if app.user != null %}
            {% for rol in user %}
                {% for rol1 in rol.roles %}
                    {% if app.user.username == rol.username and rol1 == "admin" %}
                        <p><a class="enlaceboton" href="{{ path('editarPelicula', {'id' : pelicula.id}) }}">Editar pelicula</a></p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/proyecto/peliculaActualizada.html.twig
{% extends 'base.html.twig' %}

{% block title %}CinemaPlus-ActualizaPelicula{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ path('inicio') }}">Inicio</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ path('editarPelicula', {'id' : pelicula.id}) }}">Editar pelicula</a>
        </li>
    </ul>
</div>
{% endblock %}

{% block body %}
<div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
    <h2>Editar "{{ pelicula.titulo }}"</h2>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
</div>
{% endblock %}

templates/proyecto/serie.html.twig
{# templates/proyecto/noticia.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}{{ serie.Titulo }}{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ path('inicio') }}">Inicio</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ path('serie', {'id': serie.id}) }}">{{ serie.Titulo }}</a>
        </li>
    </ul>
</div>
{% endblock %}
{% block body %}
    <div class="row">

        <div class="col-12 col-sm-8 col-xl-3 detallePeli">
            <img src="{{ asset('images/serie' ~ serie.id ~ '.jpg') }}" alt={{ serie.titulo }}/>
        </div>
        <div class="col-12 col-sm-8 col-xl-8 detallePeli">
            <h2>Título: {{ serie.Titulo }}</h2>
            <p><strong>Resumen:</strong> {{ serie.Resumen }}</p>
            <p><strong>Actores:</strong> {{ serie.Actores }}</p>
            <p><strong>Número de temporadas:</strong> {{ serie.Temporadas }}</p>
            <p><strong>Número de capitulos:</strong> {{ serie.Capitulos }}</p>
            <p><strong>Género:</strong> {{ serie.Genero }}</p>
            {% if serie.valoracions.count() == 0 %}
                <p><strong>Valoración media:</strong> Esta serie aún no ha sido valorada.</p>
            {% else %}
                {% set suma = 0 %}
                {% for valoracion in serie.valoracions %}
                    {% set numeros = valoracion.valoracion %}
                    {% set suma = numeros + suma %}
                {% endfor %}
                {% set media = suma / serie.valoracions.count() %}
                <p><strong>Valoración media:</strong> {{ media|round(1, 'floor') }}/10</p>
            {% endif %}
            <br />
            {{ form_start(form) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
    </div>
    <br /><br />
    <div class="row comentario">
        {{ form_start(form2) }}
        {{ form_widget(form2) }}
        {{ form_end(form2) }}

        <ul>
        {% for comentario in serie.comentarios %}
            <li class='bloqueComentario'>
                <p>
                    {% if comentario.Autor != null %}
                        <strong>{{ comentario.Autor.username }}</strong>
                    {% else %}
                        <strong>Anónimo</strong>
                    {% endif %}
                    en {{ comentario.fecha|date("d/m/Y") }}:
                </p>
                <p>{{ comentario.texto }}</p>
            </li>
        {% else %}
            <li>No hay comentarios</li>
        {% endfor %}
        </ul>
    </div>

    <br /><br />
    <div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
        <p><a class="enlaceboton" href="{{ path('descargarPDFSerie', {'id' : serie.id}) }}">Descargar PDF</a></p>
    </div>

    <div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
        {% if app.user != null %}
            {% for rol in user %}
                {% for rol1 in rol.roles %}
                    {% if app.user.username == rol.username and rol1 == "admin" %}
                        <p><a class="enlaceboton" href="{{ path('borrarSerie', {'id' : serie.id}) }}">Borrar serie</a></p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
        {% if app.user != null %}
            {% for rol in user %}
                {% for rol1 in rol.roles %}
                    {% if app.user.username == rol.username and rol1 == "admin" %}
                        <p><a class="enlaceboton" href="{{ path('editarSerie', {'id' : serie.id}) }}">Editar serie</a></p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/proyecto/seriesBuscadas.html.twig
{% extends 'base.html.twig' %}

{% block title %}CinemaPlus-ListaSeries{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ path('inicio') }}">Inicio</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ path('peliculas') }}">Peliculas</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ path('series') }}">Series</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ path('register') }}">Registrar</a>
        </li>
        {% if app.user != null %}
        <li class="nav-item">
            <a class="nav-link" href="{{ path('logout') }}">Salir</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{{ path('login') }}">Login</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

{% block body %}
<div class="container-fluid col-12 col-sm-12 col-xl-12 MargenSuper">
    <h2>Buscador de Series</h2>
    <br />
    <h4>Has buscado '{{ search.buscar }}'</h4>
    <br /><br />
    <div class="col-4 col-sm-4 col-xl-4">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
    <br /><br />
    {% for serie in series %}
        <div class="row">
            <div class="col-12 col-lg-12 col-xl-4">
                <a href="{{ path('serie', {'id': serie.id}) }}"><img src="{{ asset('images/serie' ~ serie.id ~ '.jpg') }}" alt={{ serie.titulo }} class="img-responsive fit-image imagenLista"></a>
            </div>
            <div class="col-12 col-lg-12 col-xl-8">
                <a class="enlacePeli" href="{{ path('serie', {'id': serie.id}) }}"><h3>{{ serie.titulo }}</h3></a>
                <p>{{ serie.actores }}</p>
                <p>{{ serie.resumen }}</p>
                <a class="enlacePeli" href="{{ path('serie', {'id': serie.id}) }}"><p>Leer mas...</p></a>
            </div>
        </div>
        <br /><br />
    {% endfor %}
</div>
{% endblock %}